### ISSUE TITLE
GeoNode DNS configuration to be reviewed

### ISSUE THREAD

**Issue by EddyCatt** [geosolutions-it/UNMISS-GeoStory#36]
We have installed a GeoNode instance on UN Azure cloud, on Ip address 10.208.63.5, accessible though remote desktop

https://docs.google.com/document/d/1S4ZaOFhIEgS-cupQO7IoR-W6AO0Q0ZcE/edit#heading=h.d1stup66ocad

After asking us to fill the cloud gateway publication form

https://docs.google.com/spreadsheets/d/1bqqtAJ4PB9Gq-xaN-H_m9BAafD41E6HV/edit#gid=820597080

the Client (UN team cloud for UNMISS) has defined the following DNS for the GeoNode portal, hosted by UN Azure cloud

southsudanmaps-dev.un.org (IP address: 10.208.1.41)

Issue is that we're currently able to access only to the geoserver page (southsudanmaps-dev.un.org/geoserver) but not to the home page  which shows the Apache Tomcat/9.0.56 page

They also sent us the following updates...

![image.png](https://images.zenhubusercontent.com/60ec432524dbe15f941a6cd6/8f17c7f0-e709-416d-bfc3-ae298971763c)

**Comment by lpasquali** [comment]
Hello @EddyCatt @randomorder 
from what I see they have put behind the balancer the geoserver application on port 8080 (10.208.63.6) and not the geonode one.
That is why we see on / a tomcat page (geoserver's tomcat) and /geoserver url seemed to be in place, but it isn't because the balancer is not pointing to 10.208.63.5 on port 80 as it should.
Looking a bit further on how geonode was configured ( https://docs.google.com/document/d/1-ZQMU-a-cadwlz0b14vK25t0ksJIF1Yogcqmf8Xhlc8/edit#) I see it is configured by ip address, this is why if you try to login to http://southsudanmaps-dev.un.org/geoserver you will get redirected to http://10.208.63.5/ as per oauth configuration in geoserver, for so geonode's env should be updated for southsudanmaps-dev.un.org host

**Comment by EddyCatt** [comment]
I've asked to the Client to reconfigure Load Balancer to point to the geonode application, 10.208.63.5 on port 80, instead of  geoserver application, 10.208.63.6 on port 8080. We'll hen reconfigure geonode accordingly



Please redirect it correctly and we'll then reconfigure geonode accordingly

**Comment by randomorder** [comment]
news @EddyCatt ?

**Comment by EddyCatt** [comment]
No news, they're struggling to address some other big incident at UNHQ Data Centre...

**Comment by EddyCatt** [comment]
@randomorder, we've just received this message from UN

we have updated the backend server IP and the port.

Subscription:  OITC-TOS-DEV     
geoserver (computer name)      
10.208.63.6 -> 10.208.63.5           
http/8080 --> http/80

Please validate

**Comment by afabiani** [comment]
@randomorder I guess I need help logging in to the server... I don't remember how to do that

**Comment by randomorder** [comment]
windows remote desktop
![image](https://user-images.githubusercontent.com/5264230/156363005-cf1f67ab-ca0c-43a6-b509-54f56ee3d294.png)

username is: adm.aparma3@global.un.org
passwd: see [doc](https://docs.google.com/document/d/1-ZQMU-a-cadwlz0b14vK25t0ksJIF1Yogcqmf8Xhlc8/edit#)

**Comment by afabiani** [comment]
![image](https://user-images.githubusercontent.com/1278021/156364123-a985b308-ea46-45c0-be25-4978d349991a.png)

![image](https://user-images.githubusercontent.com/1278021/156364149-e27bd253-1507-435f-9dc8-4f1eee939ef3.png)

**Comment by randomorder** [comment]
No luck @EddyCatt 

Looks like the proxy is not pointing to the right machine or is not able to connect to it. 

A call with the technical people would be best if possble to speed things up

**Comment by EddyCatt** [comment]
After technical call, the DNS seems to work. 
The issue was caused by a wrong configuration of the an health checks parameter of the load balancer

**Comment by afabiani** [comment]
The proxy (or whatever they have put in place) does not forwards the required/correct headers.

Currently, in order for the auth process to be correctly achieved by Django, we need the proxy passing at least the following headers:

 - $host (which must be equal to the domain name, **not** the machine IP)
 - $port (the `HTTPS` one)
 - $cookies

For reference, here below I'm going to list all the headers required by the `UWSGI` proxy pass on `NGINX`

```
  proxy_connect_timeout       600;
  proxy_send_timeout          600;
  proxy_read_timeout          600;
  send_timeout                600;
  proxy_redirect              off;
  proxy_set_header            Host $host;
  proxy_set_header            X-Real-IP $remote_addr;
  proxy_set_header            X-Forwarded-Host $server_name;
  proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header            X-Forwarded-Proto $scheme;
```

**Comment by afabiani** [comment]
@randomorder @lpasquali here below the steps to fix several issues:

## 1. CSW out of memory issue due to Ubuntu Lib libexpath1 version
sudo apt-get install libexpat1=2.2.9-1build1 libexpat1-dev=2.2.9-1build1

## 2. NGINX/Proxy does not correctly forward the Referer and the protocol schema
sudo vim /etc/nginx/sites-enabled/geonode

(everywhere)

proxy_set_header            Host southsudanmaps-dev.un.org;
proxy_set_header            X-Real-IP $remote_addr;
proxy_set_header            X-Forwarded-Host southsudanmaps-dev.un.org;
proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header            X-Forwarded-Proto https;
proxy_pass_header           Set-Cookie;
proxy_hide_header           X-Frame-Options;

## 3. CSRF Issues on login
vim UNMISS_geonode/settings.py

SESSION_COOKIE_SECURE = ast.literal_eval(os.environ.get('SESSION_COOKIE_SECURE', 'True'))
CSRF_COOKIE_SECURE = ast.literal_eval(os.environ.get('CSRF_COOKIE_SECURE', 'True'))
CSRF_COOKIE_HTTPONLY = ast.literal_eval(os.environ.get('CSRF_COOKIE_HTTPONLY', 'False'))
CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN', '.un.org')
CSRF_TRUSTED_ORIGINS = ast.literal_eval(os.environ.get('CSRF_TRUSTED_ORIGINS', ALLOWED_HOSTS))
USE_X_FORWARDED_HOST = ast.literal_eval(os.environ.get('USE_X_FORWARDED_HOST', 'True'))

-----------------------------------------------------------------------------------
sudo vim /etc/uwsgi/apps-enabled/geonode.ini

# Session/Access Control
env = LOCKDOWN_GEONODE=False
env = CORS_ORIGIN_ALLOW_ALL=True
env = SESSION_COOKIE_SECURE=True
env = CSRF_COOKIE_SECURE=True
env = CSRF_COOKIE_HTTPONLY=False
env = CSRF_TRUSTED_ORIGINS="['https://*.un.org']"
env = USE_X_FORWARDED_HOST=True
env = X_FRAME_OPTIONS=ALL
env = SESSION_EXPIRED_CONTROL_ENABLED=True
env = DEFAULT_ANONYMOUS_VIEW_PERMISSION=True
env = DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION=True

-----------------------------------------------------------------------------------
vim .env

# Session/Access Control
LOCKDOWN_GEONODE=False
CORS_ORIGIN_ALLOW_ALL=True
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_SECURE=True
CSRF_COOKIE_HTTPONLY=False
CSRF_TRUSTED_ORIGINS="['https://*.un.org']"
CSRF_COOKIE_DOMAIN=.un.org
USE_X_FORWARDED_HOST=True
X_FRAME_OPTIONS=ALL
SESSION_EXPIRED_CONTROL_ENABLED=True
DEFAULT_ANONYMOUS_VIEW_PERMISSION=True
DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION=True

## 4. Migrate all the datasets to the new DNS
From the GeoServer admin GUI:
 - proxyBaseURL = https://southsudanmaps-dev.un.org/geoserver
 - geofence role service = https://southsudanmaps-dev.un.org
 - geonode_oauth2 = https://southsudanmaps-dev.un.org (everywhere)

From the GeoNode admin GUI:
 - Site = https://southsudanmaps-dev.un.org
 - Oauth2 > Apps > GeoServer > Redirect URI = https://southsudanmaps-dev.un.org/geoserver/index.html

-----------------------------------------------------------------------------------
./manage.sh migrate_baseurl --source-address=http://http://10.208.63.5 --target-address=https://southsudanmaps-dev.un.org
./manage.sh migrate_baseurl --source-address=10.208.63.5 --target-address=southsudanmaps-dev.un.org

./manage.sh set_all_layers_metadata -d -p

-----------------------------------------------------------------------------------
./manage.sh shell

import json
from django_jsonfield_backport.features import extend_features
from django.db import connection

from geonode.geoapps.models import GeoAppData
from mapstore2_adapter.api.models import MapStoreData

extend_features(connection)

for _app in GeoAppData.objects.all():
    _blob = _app.blob.replace('http://10.208.63.5', 'https://southsudanmaps-dev.un.org')
    GeoAppData.objects.filter(id=_app.id).update(blob=_blob)

for _app in MapStoreData.objects.all():
    _blob = json.dumps(_app.blob)
    _blob = _blob.replace('http://10.208.63.5', 'https://southsudanmaps-dev.un.org')
    _blob = json.loads(_blob)
    MapStoreData.objects.filter(id=_app.id).update(blob=_blob)

**Comment by ElenaGallo** [comment]
@afabiani here are the problems I encountered after my tests:

**1_** It is not possible to uploaded layer. Error on console:

> Failed to load resource: the server responded with a status of 403 (Forbidden)

![1upload](https://user-images.githubusercontent.com/56537133/157426686-a464ad4d-0231-4b3e-b1b6-09c6a2fe22f0.png)

**2_**  It is not possible to Save a new map or an existed one. Error on console:

> POST https://southsudanmaps-dev.un.org/mapstore/rest/resources/?full=true 403 (Forbidden)

**how to reproduce**
- Open a new map
- Edit it
- Click on Options > Save

**3_** The Save option is not present for a new geostory and dashbaord.

**how to reproduce**
- Open a new geostory or dashbaord
- Edit it
- Click on Options

*Current Result*

![3dash](https://user-images.githubusercontent.com/56537133/157426790-be35ad7e-d50c-4367-af48-e1621888ac3b.png)

**4_** It is not possible to save an existed geostory and dashbaord. Error on console: 

> GET https://southsudanmaps-dev.un.org/proxy/?url=https%3A%2F%2F10.208.63.5%3A80%2Fapi%2Fv2%2Fresources%2F157 500 
(HTTPSConnectionPool(host='10.208.63.5', port=80): Max retries exceeded with url: /api/v2/resources/157 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])"))))
